import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

async function getLogo() {
  const res = await fetch("http://localhost:1337/api/logo?populate=*");
  const json = await res.json();
  console.log("SERVER LOG - Strapi URL:", process.env.NEXT_PUBLIC_STRAPI_URL);
  return json.data?.SiteLogo?.url || null;
}


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const logoUrl = await getLogo();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar data={'666'} logo={logoUrl} />
        {children}
        <Footer logo={logoUrl} />
        </body>
    </html>
  );
}
