import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

// Funzione per il Logo
async function getLogo() {
  const res = await fetch("http://localhost:1337/api/logo?populate=*");
  const json = await res.json();
  return json.data?.SiteLogo?.url || null;
}

// NUOVA FUNZIONE: Funzione per la Navigazione
async function getNavigation() {
  const res = await fetch("http://localhost:1337/api/navigation?populate=*");
  if (!res.ok) return null;
  const json = await res.json();

  
  // Restituiamo direttamente l'oggetto che contiene menuItem
  return json.data || null; 
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Eseguiamo entrambi i fetch
  const logoUrl = await getLogo();
  const navData = await getNavigation();
    // LOGGA QUI per vedere la struttura esatta nel terminale di VS Code
  console.log("NAV DATA DEBUG:", JSON.stringify(navData, null, 2));

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Passiamo navData invece di '666' */}
        <Navbar data={navData} logo={logoUrl} />
        
        <main className="flex-grow">
          {children}
        </main>

        <Footer logo={logoUrl} />
      </body>
    </html>
  );
}